---
services:
  ckan:
    build:
      context: ../
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ../extensions
          target: /app/extensions
        - action: sync+restart
          path: ../src
          target: /app/src
        - action: rebuild
          path: ../compose-dev
        - action: rebuild
          path: ../Dockerfile
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
      solr:
        condition: service_healthy
        restart: true
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    env_file:
      - ${PWD}/config/db/.env
      - ${PWD}/config/ckan/.env
    volumes:
      - ckan_data:/app/data

volumes:
  ckan_data:
